# frozen_string_literal: true

require_relative "lib/gir_ffi-atspi/version"

Gem::Specification.new do |spec|
  spec.name = "gir_ffi-atspi"
  spec.version = GirFFIAtspi::VERSION
  spec.authors = ["Matijs van Zuijlen"]
  spec.email = ["matijs@matijs.net"]

  spec.summary = "GirFFI-based bindings for Atspi"
  spec.description =
    "Bindings for Atspi generated by GirFFI, with an eclectic set of overrides."
  spec.homepage = "http://www.github.com/mvz/gir_ffi-atspi"
  spec.license = "LGPL-2.1"
  spec.required_ruby_version = ">= 3.1.0"

  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://github.com/mvz/gir_ffi-atspi"
  spec.metadata["changelog_uri"] = "https://github.com/mvz/gir_ffi-atspi/blob/master/Changelog.md"
  spec.metadata["rubygems_mfa_required"] = "true"

  spec.files = File.read("Manifest.txt").split
  spec.require_paths = ["lib"]

  spec.add_dependency "gir_ffi", "~> 0.18.0"
end
